import type { Config } from 'tailwindcss';

const config: Config = {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      fontFamily: {
        sans: ['Geist', 'Inter', 'Plus Jakarta Sans', 'system-ui', '-apple-system', 'sans-serif'],
        display: ['Geist', 'sans-serif'],
        headline: ['Geist', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        mono: ['JetBrains Mono', 'ui-monospace', 'SF Mono', 'monospace'],
        'metric-stat': ['Geist', 'sans-serif'],
        'label-caps': ['Geist', 'sans-serif'],
        'label-md': ['Geist', 'sans-serif'],
        'title-sm': ['Geist', 'sans-serif'],
        'headline-md': ['Geist', 'sans-serif'],
        'headline-lg': ['Geist', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'body-sm': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'display': ['36px', { lineHeight: '44px', letterSpacing: '-0.03em', fontWeight: '600' }],
        'headline-lg': ['28px', { lineHeight: '36px', letterSpacing: '-0.025em', fontWeight: '600' }],
        'headline-md': ['20px', { lineHeight: '28px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'title-sm': ['15px', { lineHeight: '22px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'metric-stat': ['24px', { lineHeight: '30px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'label-caps': ['11px', { lineHeight: '14px', letterSpacing: '0.06em', fontWeight: '600' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.01em', fontWeight: '500' }],
        'body-lg': ['15px', { lineHeight: '24px', fontWeight: '400' }],
        'body-md': ['13px', { lineHeight: '20px', fontWeight: '400' }],
        'body-sm': ['12px', { lineHeight: '18px', fontWeight: '400' }],
      },
      spacing: {
        'space-xs': '0.25rem',
        'space-sm': '0.5rem',
        'space-md': '0.75rem',
        'space-lg': '1rem',
        'space-xl': '1.5rem',
        'gutter': '1rem',
        'gutter-md': '1.25rem',
        'gutter-lg': '1.5rem',
        'margin': '1rem',
        'margin-md': '1.5rem',
        'margin-lg': '2rem',
      },
      colors: {
        background: 'rgb(var(--color-bg) / <alpha-value>)',
        foreground: 'rgb(var(--color-fg) / <alpha-value>)',
        card: {
          DEFAULT: 'rgb(var(--color-card) / <alpha-value>)',
          foreground: 'rgb(var(--color-card-fg) / <alpha-value>)',
        },
        muted: {
          DEFAULT: 'rgb(var(--color-muted) / <alpha-value>)',
          foreground: 'rgb(var(--color-muted-fg) / <alpha-value>)',
        },
        border: 'rgb(var(--color-border) / <alpha-value>)',
        primary: {
          DEFAULT: 'rgb(var(--color-primary) / <alpha-value>)',
          foreground: 'rgb(var(--color-primary-fg) / <alpha-value>)',
          container: 'rgb(var(--color-primary-container) / <alpha-value>)',
          fixed: 'rgb(var(--color-primary-fixed) / <alpha-value>)',
        },
        'primary-container': 'rgb(var(--color-primary-container) / <alpha-value>)',
        'on-primary-container': 'rgb(var(--color-on-primary-container) / <alpha-value>)',
        'primary-fixed': 'rgb(var(--color-primary-fixed) / <alpha-value>)',
        'on-primary-fixed': 'rgb(var(--color-on-primary-fixed) / <alpha-value>)',
        'on-primary': 'rgb(var(--color-primary-fg) / <alpha-value>)',
        'on-background': 'rgb(var(--color-fg) / <alpha-value>)',
        'on-surface': 'rgb(var(--color-on-surface) / <alpha-value>)',
        'on-surface-variant': 'rgb(var(--color-on-surface-variant) / <alpha-value>)',
        secondary: {
          DEFAULT: 'rgb(var(--color-secondary) / <alpha-value>)',
          container: 'rgb(var(--color-secondary-container) / <alpha-value>)',
        },
        'secondary-container': 'rgb(var(--color-secondary-container) / <alpha-value>)',
        tertiary: {
          DEFAULT: 'rgb(var(--color-tertiary) / <alpha-value>)',
          container: 'rgb(var(--color-tertiary-container) / <alpha-value>)',
        },
        'tertiary-container': 'rgb(var(--color-tertiary-container) / <alpha-value>)',
        surface: {
          DEFAULT: 'rgb(var(--color-surface) / <alpha-value>)',
          container: 'rgb(var(--color-surface-container) / <alpha-value>)',
          'container-lowest': 'rgb(var(--color-surface-lowest) / <alpha-value>)',
          'container-low': 'rgb(var(--color-surface-low) / <alpha-value>)',
          'container-high': 'rgb(var(--color-surface-high) / <alpha-value>)',
          'container-highest': 'rgb(var(--color-surface-highest) / <alpha-value>)',
        },
        'surface-container': 'rgb(var(--color-surface-container) / <alpha-value>)',
        'surface-container-lowest': 'rgb(var(--color-surface-lowest) / <alpha-value>)',
        'surface-container-low': 'rgb(var(--color-surface-low) / <alpha-value>)',
        'surface-container-high': 'rgb(var(--color-surface-high) / <alpha-value>)',
        'surface-container-highest': 'rgb(var(--color-surface-highest) / <alpha-value>)',
        outline: {
          DEFAULT: 'rgb(var(--color-outline) / <alpha-value>)',
          variant: 'rgb(var(--color-outline-variant) / <alpha-value>)',
        },
        'outline-variant': 'rgb(var(--color-outline-variant) / <alpha-value>)',
      },
      borderRadius: {
        token: 'var(--radius)',
      },
      boxShadow: {
        'xs':    'var(--shadow-xs)',
        'sm':    'var(--shadow-sm)',
        'md':    'var(--shadow-md)',
        'lg':    'var(--shadow-lg)',
        'xl':    'var(--shadow-xl)',
        'float': 'var(--shadow-float)',
        'inner-glow': 'inset 0 1px 0 rgb(255 255 255 / 0.06)',
      },
      transitionTimingFunction: {
        'out-expo': 'cubic-bezier(0.16, 1, 0.3, 1)',
        'spring':   'cubic-bezier(0.34, 1.56, 0.64, 1)',
      },
      transitionDuration: {
        'fast':   '150ms',
        'base':   '250ms',
        'slow':   '400ms',
        'reveal': '600ms',
      },
      keyframes: {
        'fade-in': {
          from: { opacity: '0' },
          to:   { opacity: '1' },
        },
        'slide-up': {
          from: { opacity: '0', transform: 'translateY(100%)' },
          to:   { opacity: '1', transform: 'translateY(0)' },
        },
        'scale-up': {
          from: { opacity: '0', transform: 'scale(0.95) translateY(4px)' },
          to:   { opacity: '1', transform: 'scale(1) translateY(0)' },
        },
        'fade-up': {
          from: { opacity: '0', transform: 'translateY(12px)' },
          to:   { opacity: '1', transform: 'translateY(0)' },
        },
        'scale-in': {
          from: { opacity: '0', transform: 'scale(0.96)' },
          to:   { opacity: '1', transform: 'scale(1)' },
        },
        'slide-up-toast': {
          from: { opacity: '0', transform: 'translateY(16px) scale(0.97)' },
          to:   { opacity: '1', transform: 'translateY(0) scale(1)' },
        },
        'shimmer': {
          '0%':   { backgroundPosition: '200% 0' },
          '100%': { backgroundPosition: '-200% 0' },
        },
        'breathe': {
          '0%, 100%': { transform: 'scale(1)', opacity: '0.9' },
          '50%':      { transform: 'scale(1.15)', opacity: '1' },
        },
      },
      animation: {
        'fade-in':    'fade-in 200ms ease-out both',
        'slide-up':   'slide-up 340ms cubic-bezier(0.16, 1, 0.3, 1) both',
        'scale-up':   'scale-up 220ms cubic-bezier(0.34, 1.56, 0.64, 1) both',
        'fade-up':    'fade-up 400ms cubic-bezier(0.16, 1, 0.3, 1) both',
        'scale-in':   'scale-in 400ms cubic-bezier(0.34, 1.56, 0.64, 1) both',
        'slide-up-toast': 'slide-up-toast 350ms cubic-bezier(0.34, 1.56, 0.64, 1) both',
        'shimmer':    'shimmer 1.8s ease-in-out infinite',
        'breathe':    'breathe 3s ease-in-out infinite',
      },
    },
  },
  plugins: [],
};

export default config;
